apiVersion: apps/v1
kind: Deployment
metadata:
  name: pms-client
  namespace: default
  labels:
    app: pms-client
spec:
  selector:
    matchLabels:
      app: pms-client
  template:
    metadata:
      labels:
        app: pms-client
    spec:
      containers:
        - name: pms-client
          image: rizwans21/pms_client
          ports:
            - containerPort: 3000
